### ISSUE TITLE
Feature request: validation depending on other variables in same message

### ISSUE THREAD

**Issue by johanbrandhorst** [mwitkow/go-proto-validators#12]
This will probably be hilariously complicated to cover all the cases, but I thought a cool idea would be if you could have a message like this:

```
message MyMessage {
    int32 my_int = 1;
    int32 my_other_int = 2;
}
```

I would like to validate that `my_other_int` is a certain value relative to the value of `my_int`. For example:

```
message MyMessage {
    int32 my_int = 1;
    int32 my_other_int = 2 [(validator.field = { int_val: my_int / 2 })];
}
```

Mostly thinking out loud, and maybe this is way too complicated. Would be interested in hearing thoughts on it.

**Comment by mwitkow** [comment]
The problem here would be that expressions such as `my_int / 2` would need to be as strings, otherwise they would not pass the `protoc` parsing. 

Definitely won't do it using that expression, but could potentially have a 
```
{
  maths: {
     field: 1
     op: division
  } 
}
```

But that'll be ugly.

I think this is too complicated and would be easier solved by the user building their own custom `Validate` function.

**Comment by johanbrandhorst** [comment]
Yeah, fair enough. I'll close this as it was mostly a thought I had, thanks for the feedback.
